<?= "<?php\n" ?>

namespace <?= $namespace ?>;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use <?= $entity_namespace ?>;
use <?= $interface_namespace ?>;

use Doctrine\Persistence\ManagerRegistry;

/**
 * <?= $class_name . "\n" ?>
 *
 * This class was generated by ivoz:make:repositories command.
 * Add your own custom repository methods below.
 *
 * @template-extends ServiceEntityRepository<<?= $entity_classname ?>>
 */
class <?= $class_name ?> extends ServiceEntityRepository implements <?= $interface_name ?>

{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, <?= $entity_classname ?>::class);
    }
}