services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Symfony\Bundle\MakerBundle\Util\ComposerAutoloaderFinder:
    arguments:
      $rootNamespace: ''
  Symfony\Bundle\MakerBundle\Util\AutoloaderUtil: ~

  IvozDevTools\EntityGeneratorBundle\Generator:
    arguments:
      $fileManager: '@maker.file_manager'
      $namespacePrefix: ''
      $autoloaderUtil: '@Symfony\Bundle\MakerBundle\Util\AutoloaderUtil'

  IvozDevTools\EntityGeneratorBundle\Doctrine\Mapping\MappingGenerator:
    arguments:
      $fileManager: '@maker.file_manager'

  IvozDevTools\EntityGeneratorBundle\Maker\MakeEntities:
    arguments:
      $fileManager: '@maker.file_manager'
      $doctrineHelper: '@maker.doctrine_helper'
      $generator: '@IvozDevTools\EntityGeneratorBundle\Generator'

  IvozDevTools\EntityGeneratorBundle\Command\MakeEntitiesCommand:
    arguments:
      $maker: '@IvozDevTools\EntityGeneratorBundle\Maker\MakeEntities'
      $fileManager: '@maker.file_manager'
      $generator: '@IvozDevTools\EntityGeneratorBundle\Generator'
    tags: [{ name: 'console.command' }]

  provider.make.entities:
    deprecated: "%service_id% is deprecated: use ivoz:make:entities instead"
    class: IvozDevTools\EntityGeneratorBundle\Command\MakeEntitiesCommand
    arguments:
      $maker: '@IvozDevTools\EntityGeneratorBundle\Maker\MakeEntities'
      $fileManager: '@maker.file_manager'
      $generator: '@IvozDevTools\EntityGeneratorBundle\Generator'
    tags: [{ name: 'console.command', command: 'provider:make:entities' }]

  IvozDevTools\EntityGeneratorBundle\Maker\MakeInterfaces:
    arguments:
      $fileManager: '@maker.file_manager'
      $doctrineHelper: '@maker.doctrine_helper'
      $generator: '@IvozDevTools\EntityGeneratorBundle\Generator'

  IvozDevTools\EntityGeneratorBundle\Command\MakeInterfacesCommand:
    arguments:
      $maker: '@IvozDevTools\EntityGeneratorBundle\Maker\MakeInterfaces'
      $fileManager: '@maker.file_manager'
      $generator: '@IvozDevTools\EntityGeneratorBundle\Generator'
    tags: [{ name: 'console.command' }]

  provider.make.interfaces:
    deprecated: "%service_id% is deprecated: use ivoz:make:entities instead"
    class: IvozDevTools\EntityGeneratorBundle\Command\MakeEntitiesCommand
    arguments:
      $maker: '@IvozDevTools\EntityGeneratorBundle\Maker\MakeInterfaces'
      $fileManager: '@maker.file_manager'
      $generator: '@IvozDevTools\EntityGeneratorBundle\Generator'
    tags: [{ name: 'console.command', command: 'provider:make:entities' }]

  IvozDevTools\EntityGeneratorBundle\Maker\MakeOrmMapping:
    arguments:
      $fileManager: '@maker.file_manager'
      $doctrineHelper: '@maker.doctrine_helper'
      $mappingGenerator: '@IvozDevTools\EntityGeneratorBundle\Doctrine\Mapping\MappingGenerator'

  IvozDevTools\EntityGeneratorBundle\Command\MakeOrmMappingCommand:
    arguments:
      $maker: '@IvozDevTools\EntityGeneratorBundle\Maker\MakeOrmMapping'
      $fileManager: '@maker.file_manager'
      $mappingGenerator: '@IvozDevTools\EntityGeneratorBundle\Doctrine\Mapping\MappingGenerator'
    tags: [ { name: 'console.command' } ]

  provider.make.orm.entity:
    deprecated: "%service_id% is deprecated: use ivoz:make:orm:mapping instead"
    class: IvozDevTools\EntityGeneratorBundle\Command\MakeOrmMappingCommand
    arguments:
      $maker: '@IvozDevTools\EntityGeneratorBundle\Maker\MakeOrmMapping'
      $fileManager: '@maker.file_manager'
      $mappingGenerator: '@IvozDevTools\EntityGeneratorBundle\Doctrine\Mapping\MappingGenerator'
    tags: [ { name: 'console.command', command: 'provider:make:orm:mapping' } ]
    
  #    REPOSITORY SERVICE
  IvozDevTools\EntityGeneratorBundle\Maker\MakeRepositories:
    arguments:
      $fileManager: '@maker.file_manager'
      $doctrineHelper: '@maker.doctrine_helper'
      $generator: '@IvozDevTools\EntityGeneratorBundle\Generator'

  IvozDevTools\EntityGeneratorBundle\Command\MakeRepositoriesCommand:
    arguments:
      $maker: '@IvozDevTools\EntityGeneratorBundle\Maker\MakeRepositories'
      $fileManager: '@maker.file_manager'
      $generator: '@IvozDevTools\EntityGeneratorBundle\Generator'
    tags: [ { name: 'console.command' } ]

  provider.make.repositories:
    deprecated: "%service_id% is deprecated: use ivoz:make:repositories instead"
    class: IvozDevTools\EntityGeneratorBundle\Command\MakeRepositoriesCommand
    arguments:
      $maker: '@IvozDevTools\EntityGeneratorBundle\Maker\MakeRepositories'
      $fileManager: '@maker.file_manager'
      $generator: '@IvozDevTools\EntityGeneratorBundle\Generator'
    tags: [ { name: 'console.command', command: 'provider:make:repositories' } ]

  IvozDevTools\EntityGeneratorBundle\Command\UpdateServiceCollectionsCommand:
    tags: [{ name: 'console.command' }]

  provider.update.service_collections:
    deprecated: "%service_id% is deprecated: use ivoz:update:service_collections instead"
    class: IvozDevTools\EntityGeneratorBundle\Command\UpdateServiceCollectionsCommand
    tags: [{ name: 'console.command', command: 'provider:update:service_collections'}]

  IvozDevTools\EntityGeneratorBundle\Doctrine\Metadata\ClassMetadataFactory: ~

doctrine:
  orm:
    class_metadata_factory_name:  IvozDevTools\EntityGeneratorBundle\Doctrine\Metadata\ClassMetadataFactory
