services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  IvozDevTools\EntityGeneratorBundle\Generator:
    arguments:
      $fileManager: '@maker.file_manager'
      $namespacePrefix: ''

  IvozDevTools\EntityGeneratorBundle\Maker\MakeEntities:
    arguments:
      $fileManager: '@maker.file_manager'
      $doctrineHelper: '@maker.doctrine_helper'
      $generator: '@IvozDevTools\EntityGeneratorBundle\Generator'
      $projectDirectory: '%kernel.project_dir%'
      $entityClassGenerator: '@maker.entity_class_generator'

  IvozDevTools\EntityGeneratorBundle\Command\MakeEntitiesCommand:
    arguments:
      $maker: '@IvozDevTools\EntityGeneratorBundle\Maker\MakeEntities'
      $fileManager: '@maker.file_manager'
      $generator: '@IvozDevTools\EntityGeneratorBundle\Generator'
    tags: [{ name: 'console.command'}]

  IvozDevTools\EntityGeneratorBundle\Command\UpdateServiceCollectionsCommand:
    tags: [{ name: 'console.command'}]