services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  IvozDevTools\CommandlogBundle\Command\:
    resource: '%kernel.project_dir%/vendor/irontec/ivoz-dev-tools/CommandlogBundle/Command/*'
    tags: [{ name: 'console.command'}]

  ivoz.commandlog.show:
    class: IvozDevTools\CommandlogBundle\Command\ShowCommand
    tags: [{ name: 'console.command', command: 'ivoz:commandlog:show' }]